name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: & { { secrets.SSH_HOST } } #IP address of the server you wish to ssh into
          key: & { { secrets.KEY } } #Private or public key of the server
          username: & { { secrets.SSH_USERNAME } } #User of the server you want to ssh into

          script: |
            mkdir test #create folder you want to deploy to in the live server
            cd test #enter or cd into the folder
            git clone git@github.com:Andrii-Yukhymenko/Yukhym-Cryptor.git #clone the repository tinto the folder
            echo 'Deployment successful to digital ocean' #Message to be displayed when deploy is successful
