name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          
          script:
            cd /
            rm -rf /var/www/html/
            rm -rf /home/cloned-repo/
            cd /home
            mkdir cloned-repo
            cd cloned-repo/
            git clone https://github.com/Andrii-Yukhymenko/Yukhym-Cryptor.git
            cd cloned-repo/
            cp -r app/* /var/www/html


#name: Deploy
#
#on: [push]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Copy repository contents via scp
#        uses: Andrii-Yukhymenko/Yukhym-Cryptor@main
#        env:
#          HOST: ${{ secrets.SSH_HOST }}
#          USERNAME: ${{ secrets.SSH_USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSH_KEY }}
#        with:
#          source: "."
#          target: "/app"
#
#      - name: Executing remote command
#        uses: Andrii-Yukhymenko/Yukhym-Cryptor@main
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          USERNAME: ${{ secrets.SSH_USERNAME }}
#          PORT: ${{ secrets.PORT }}
#          KEY: ${{ secrets.SSH_KEY }}
#          script: ls

#name: Deploy
#
#on:
#  push:
#    branches: [main]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy project
#        uses: appleboy/ssh-action@v0.1.2
#        with:
#          host: $ {{ secrets.SSH_HOST }} #IP address of the server you wish to ssh into
#          key: $ {{ secrets.SSH_KEY }} #Private or public key of the server
#          username: $ { { secrets.SSH_USERNAME } } #User of the server you want to ssh into
#
#          script:
#            mkdir test
#            cd test
#            git clone git@github.com:Andrii-Yukhymenko/Yukhym-Cryptor.git
#            echo 'Deployment successful to digital ocean'

