name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy project
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: $ {{ secrets.SSH_HOST }} #IP address of the server you wish to ssh into
          key: $ {{ secrets.KEY }} #Private or public key of the server
          username: $ { { secrets.SSH_USERNAME } } #User of the server you want to ssh into

          script:
            mkdir test
            cd test
            git clone git@github.com:Andrii-Yukhymenko/Yukhym-Cryptor.git
            echo 'Deployment successful to digital ocean'
