name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /
            rm -rf /var/www/html/
            rm -rf /home/cloned-repo/
            cd /var/www
            mkdir html
            cd /home
            mkdir cloned-repo
            cd cloned-repo
            git clone https://github.com/Andrii-Yukhymenko/Yukhym-Cryptor.git
            cd Yukhym-Cryptor/
            cp -r app/* /var/www/html

# name: Build & Deploy
# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy NodeJS app
#         uses: appleboy/ssh-action@v0.1.2
#         with:
#           host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
#           key: ${{secrets.SSH_KEY}} # Private or public key of the server
#           username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          
#           script:
#             mkdir cloned-repo2
#             cd cloned-repo2/
#             git clone https://github.com/Andrii-Yukhymenko/Yukhym-Cryptor.git
